_prefs: 
  baselayer: ''
  print: true
  saveCenter: false
_properties: {}
attribution: "<a href='https://transcaucasiantrail.org' target='_blank'>&copy; TCTA &copy; OpenStreetMap</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 42.4113
  - 43.0812
  - 12
description: Style for hiking maps in the Caucasus
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - landcover
  - dense_forest
  - mechseri
  - herbaceous
  - glaciers
  - landuse
  - contour.line
  - sov-lines
  - hillshade
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - svaneti-racha-border
  - utm_lines
  - country_label_line
  - tracks_master
  - tct-route
  - features
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - peaks
  - mountain_pass
  - app_ele
  - markers
  - mud
  - notes
  - scout
  - signs
  - towers
  - mountain_peak_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
  - contour.label
maxzoom: 20
minzoom: 0
name: hikeOSMwRoutes
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7,tct.dabiwpod,tct.bayra4t9,tct.5cbwyx2h,tct.e5114113,tct.051f20bb,tct.4772ac2a"
styles: 
  - style.mss
  - road.mss
  - label.mss
  - poi.mss
  - more.mss
template: ''
