_prefs: 
  baselayer: ''
  mapid: tcta.7bafd670
  print: true
  saveCenter: false
_properties: {}
attribution: "<a href='https://transcaucasiantrail.org' target='_blank'>&copy; TCTA &copy; OpenStreetMap</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 44.3024
  - 41.3191
  - 8
description: Style for hiking maps in the Caucasus
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - landcover
  - landcover_tct
  - glaciers
  - landuse
  - contour.line
  - sov-lines
  - hillshade
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - svaneti-racha-border
  - utm_lines
  - country_label_line
  - tct_routes
  - tce_routes
  - features
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - peak-pass
  - tct_points
  - tce_points
  - photos-34ed7o
  - mountain_peak_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
  - contour.label
maxzoom: 20
minzoom: 0
name: hikeOSMwRoutes
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7,tct.879ycvvr,tct.osm_peak_pass,tct.051f20bb,tct.tct_routes,tct.tce_routes,tct.tct_points,tct.tce_points,tct.c77di1ba"
styles: 
  - style.mss
  - road.mss
  - label.mss
  - poi.mss
  - more.mss
template: ''
